# Generated by Django 2.2.1 on 2019-09-16 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IbgeCNAE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secao_id', models.CharField(max_length=2, verbose_name='id da seção')),
                ('secao_descricao', models.CharField(max_length=150, verbose_name='nome da seção')),
                ('divisao_id', models.CharField(max_length=5, verbose_name='id da divisão')),
                ('divisao_descricao', models.CharField(max_length=150, verbose_name='nome da divisão')),
                ('grupo_id', models.CharField(max_length=5, verbose_name='id do grupo')),
                ('grupo_descricao', models.CharField(max_length=150, verbose_name='nome do grupo')),
                ('classe_id', models.CharField(max_length=5, verbose_name='id da classe')),
                ('classe_descricao', models.CharField(max_length=150, verbose_name='nome da classe')),
                ('classe_observacoes', models.TextField(verbose_name='descrição da classe')),
                ('published_date', models.DateTimeField(verbose_name='data da publicação')),
                ('rel_ativo', models.BooleanField(verbose_name='ativo')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de pesquisas',
                'verbose_name_plural': 'Históricos de pesquisas',
            },
            managers=[
                ('objetos', django.db.models.manager.Manager()),
            ],
        ),
    ]
